config/routes.rb
Rails.application.routes.draw do
# ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: :all
devise_scope :user do
  get 'users/sign_up' => 'public/registrations#new', as: :new_user_registration
  post 'users/sign_up' => 'public/registrations#create', as: :create_user_registration
  get 'users/sign_in' => 'public/sessions#new', as: :new_user_session
  post 'users/sign_in' => 'public/sessions#create', as: :create_user_session
  delete 'users/sign_out' => 'public/sessions#destroy', as: :destroy_user_session
end
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: :all
devise_scope :admin do
  get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  post 'admin/sign_in' => 'admin/sessions#create', as: :create_admin_session
  delete 'admin/logout' => 'admin/sessions#destroy', as: :destroy_admin_session
end

  
  
  scope module: :public do
    root to: 'homes#top'
    delete 'bookmarks/:bookmark_id' => 'bookmarks#destroy', as: 'destroy_bookmark'
    post 'games/:game_id/bookmarks' => 'bookmarks#create', as: 'create_bookmark'
    get 'user/:id/bookmarks' => 'bookmarks#index', as: 'index_bookmark'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    post 'games/:game_id/reviews' => 'reviews#create', as: 'create_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    post 'reviews/:review_id/comments' => 'comments#create', as: 'create_comment'
    delete 'comments/:comment_id' => 'comments#destroy', as: 'destroy_comment'
    get 'games' => 'games#index'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    get 'users/mypage' => 'users#show', as: 'mypage_user'
    get 'users/edit' => 'users#edit', as: 'edit_user'
    patch 'users/update/:id' => 'users#update', as: 'update_user'#HTTPメソッドとURLが被るとルートが上から優先される(今回はupdate)ため、URLにupdateを追加して被らないようにした
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users/withdrawal'
    get '/' => 'homes#top'
    get "search" => "searches#search"
    get 'searches/index'
  end

  namespace :admin do
    get 'genres' => 'genres#index'
    post 'genres/create' => 'genres#create'
    get 'genres/:genre_id/edit' => 'genres#edit', as: 'edit_genre'
    patch 'genres/:genre_id' => 'genres#update', as: 'update_genre'
    get 'users' => 'users#index'
    get 'users/:id' => 'users#show', as: 'show_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'games' => 'games#index'
    get 'games/new' => 'games#new'
    post 'games' => 'games#create', as: 'create_game'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    delete 'games/:game_id/' => 'games#destroy', as: 'destroy_game'
    get 'games/:game_id/edit' => 'games#edit', as: 'edit_game'
    patch 'games/:game_id' => 'games#update', as: 'update_game'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    delete 'comments/:comment_id' => 'comments#destroy',as: 'destroy_comment'
    get "search" => "searches#search"
    get 'searches/index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def show
    @review = Review.find(params[:review_id])
    @comments = @review.comments.all
  end
  
  def destroy
    @review = Rreview.find(params[:review_id])
    @review.destroy
    redirect_to admin_games_path
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/show.html.erb
<div class="contaier px-5 bg-white">
  <!--reviews#show-->
  <div class="row">
    <div class="col-md-8">
      <h3>
        <%= @review.game.name %> レビュー詳細
      </h3>
    </div>
    <div class="col-md-4">
      <p>
        <%= @comments.count %>件のコメント
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag @review.user.get_profile_avatar(100,100) %>
    </div>
    <div class="col-md-7">
      <h4>
        <%= @review.user.name %>のレビュー
      </h4>
      <div>
        <%= @review.review_writing %>
      </div>
    </div>
    <div class="col-md-2">
      <p>
        <%= l @review.created_at %>
      </p>
      <%= link_to "レビューの削除", admin_destroy_review_path(@review.id), method: :delete, :class => "btn btn-danger" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h3>レビューへのコメント一覧</h3>
    </div>
    <div>
      <%= link_to "ゲーム詳細ページに戻る", admin_show_game_path(@review.game.id), method: :delete, :class => "btn btn-primary" %>
    </div>
    <!--comment#index-->
    <div class="col-md-8 review_column">
    <% @comments.each do |comment| %>
      <div class="row">
        <div class="col-md-3">
          <%= image_tag comment.user.get_profile_avatar(50,50) %>
        </div>
        <div class="col-md-6">
          <div>
            <p><%= comment.user.name %> のコメント</p>
          </div>
            <p><%= comment.comment_writing %></p>
        </div>
        <div class="col-md-3">
          <div><%= comment.created_at %></div>
          <%= link_to "コメントの削除", admin_destroy_comment_path(comment.id), method: :delete, :class => "btn btn-success" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>