config/routes.rb
Rails.application.routes.draw do
# ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: :all
devise_scope :user do
  get 'users/sign_up' => 'public/registrations#new', as: :new_user_registration
  post 'users/sign_up' => 'public/registrations#create', as: :create_user_registration
  get 'users/sign_in' => 'public/sessions#new', as: :new_user_session
  post 'users/sign_in' => 'public/sessions#create', as: :create_user_session
  delete 'users/sign_out' => 'public/sessions#destroy', as: :destroy_user_session
end
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: :all
devise_scope :admin do
  get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  post 'admin/sign_in' => 'admin/sessions#create', as: :create_admin_session
  delete 'admin/logout' => 'admin/sessions#destroy', as: :destroy_admin_session
end

  
  
  scope module: :public do
    root to: 'homes#top'
    delete 'bookmarks/:bookmark_id' => 'bookmarks#destroy', as: 'destroy_bookmark'
    post 'games/:game_id/bookmarks' => 'bookmarks#create', as: 'create_bookmark'
    get 'user/:id/bookmarks' => 'bookmarks#index', as: 'index_bookmark'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    post 'games/:game_id/reviews' => 'reviews#create', as: 'create_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    post 'reviews/:review_id/comments' => 'comments#create', as: 'create_comment'
    delete 'comments/:comment_id' => 'comments#destroy', as: 'destroy_comment'
    get 'games' => 'games#index'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    get 'users/mypage' => 'users#show', as: 'mypage_user'
    get 'users/edit' => 'users#edit', as: 'edit_user'
    patch 'users/update/:id' => 'users#update', as: 'update_user'#HTTPメソッドとURLが被るとルートが上から優先される(今回はupdate)ため、URLにupdateを追加して被らないようにした
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users/withdrawal'
    get '/' => 'homes#top'
    get "search" => "searches#search"
    get 'searches/index'
  end

  namespace :admin do
    get 'genres' => 'genres#index'
    post 'genres/create' => 'genres#create'
    get 'genres/:genre_id/edit' => 'genres#edit', as: 'edit_genre'
    patch 'genres/:genre_id' => 'genres#update', as: 'update_genre'
    get 'users' => 'users#index'
    get 'users/:id' => 'users#show', as: 'show_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'games' => 'games#index'
    get 'games/new' => 'games#new'
    post 'games' => 'games#create', as: 'create_game'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    delete 'games/:game_id/' => 'games#destroy', as: 'destroy_game'
    get 'games/:game_id/edit' => 'games#edit', as: 'edit_game'
    patch 'games/:game_id' => 'games#update', as: 'update_game'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    delete 'comments/:comment_id' => 'comments#destroy',as: 'destroy_comment'
    get "search" => "searches#search"
    get 'searches/index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  has_one_attached :profile_image
  
  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  
  validates :name, length: { in: 1..30 } 
  validates :introduction, length: { in: 1..75 }
  validates :price, numericality: true
  
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @game = Game.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @game = Game.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @game = Game.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @game = Game.where("name LIKE?","%#{word}%")
    else
      @game = Game.all
    end
  end
  
  def self.filter_price(params)
    if params[:price].present?
      case params[:price]
      when "0"
        where(price: 0)
      when "1..500"
        where(price: 1..500)
      when "501..2000"
        where(price: 501..2000)
      when "2001..5000"
        where(price: 2001..5000)
      when "5001.."
        where("price >= ?",5001)
      else
        all
      end
    else
      all
    end
  end
  
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @gamecount = Game.all.count
    @games = Game.all.filter_price(game_filter_params).page(params[:page]).per(8)
  end

  def new
    @game = Game.new
    @genres_name = Genre.all
  end

  def create
    @game = Game.new(game_params)
    if @game.save!
      flash[:notice] = "ジャンル作成に成功しました。"
      redirect_to admin_show_game_path(@game.id)
    else
      @genres_name = Genre.all
      render :new
    end
  end

  def show
    @game = Game.find(params[:game_id])
    @reviews = @game.reviews
  end

  def edit
    @game = Game.find(params[:game_id])
    @genres_name = Genre.all
  end

  def update
    @game = Game.find(params[:game_id])
    if @game.update(game_params)
      flash[:notice] = "ゲーム情報を編集しました。"
      redirect_to admin_show_game_path(@game.id)
    else
      render :edit
    end
  end

  def destroy
    game = Game.find(params[:game_id])
    game.destroy
    redirect_to admin_games_path
  end

  private
  
  def authenticate_admin!
    unless current_user.admin?
      flash[:alert] = "管理者権限が必要です。"
      redirect_to root_path # 管理者以外はトップページにリダイレクト
    end
  end
  
  def game_params
    params.require(:game).permit(:profile_image,:name,:introduction,:price,:genre_id)
  end
  
  def game_filter_params
    params.permit(:price)
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/views/admin/games/edit.html.erb
<div class="container px-5 bg-white">
  <%= form_with model: @game, url: admin_update_game_path(@game.id) do |f| %>
  <div class="row">
    <div class="col-md-8">
      <h3>ゲーム情報編集</h3>
    </div>
    <dic class="col-md-4">
      <%= link_to "ゲーム情報の削除", admin_destroy_game_path(@game.id), method: :delete, :class => "btn btn-danger", data: { confirm: "本当に削除しますか？" } %>
    </dic>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ゲーム画像</p>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.file_field :profile_image, accept:"image/*" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ゲームタイトル</p>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.text_field :name, autofocus: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ゲーム説明</p>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.text_field :introduction, autofocus: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ジャンル</p>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.select :genre_id, options_from_collection_for_select(@genres_name, :id, :genre_name) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>価格</p>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.number_field :price, autofocus: true, autocomplete: "price" %>円
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4">
      <%= f.submit "変更を保存", class:'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/games/index.html.erb
<div class ="container px-4 bg-white">
  <div class="row">
    <div class="col">
     <div class="game-title">ゲーム一覧</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 narrow-down">
      <h4>絞り込み</h4><span>(全<%= @gamecount%>件)</span>
      <p>金額</p>
      <div><%= link_to "無料", admin_games_path(price: 0), :class => "custom-button" %></div>
      <div><%= link_to "1~500円", admin_games_path(price:1..500), :class => "custom-button" %></div>
      <div><%= link_to "501~2,000円", admin_games_path(price:501..2000), :class => "custom-button" %></div>
      <div><%= link_to "2,001~5,000円", admin_games_path(price:2001..5000), :class => "custom-button" %></div>
      <div><%= link_to "5001円~", admin_games_path(price: 5001..), :class => "custom-button" %></div>
      <div><%= link_to "新規登録", admin_games_new_path, :class => "custom-button-green" %></div>
    </div>
    <div class="col-md-9 scroll">
    <% @games.each do |game| %>
      <div class="row sand">
        <div class="col-md-3">
          <div><%= image_tag game.get_profile_image(100,100) %></div>
        </div>
        <div class="col-md-5">
          <div>
            <%= link_to admin_show_game_path(game.id) do %>
              <%= game.name %>
            <% end %>
          </div>
          <div class="col-md-8 genre">
            <%= game.genre.genre_name %>
          </div>
          <div class="col-md-4"></div>
        </div>
        <div class="col-md-4">
          <div><%= l game.created_at %>(公開日)</div>
          <div>￥<%= game.price %></div>
        </div>
      </div>
    <% end %>
    <%= paginate @games %>
    </div>
  </div>
</div>

app/views/admin/games/new.html.erb
<div class="container px-5 bg-white">
  <%= form_with model: @game, url: admin_create_game_path do |f| %>
  <div class="row">
    <div class="col-md-3">
      <h3>ゲーム新規登録</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ゲーム画像</p>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.file_field :profile_image, accept:"image/*" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ゲームタイトル</p>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= f.text_field :name, autofocus: true, value:"タイトル名" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ゲーム説明</p>
    </div>
    <div class="col-md-6">
      <div class="introduction_field">
        <%= f.text_area :introduction, size: "50", autofocus: true, value:"ここに説明文を記入します。" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>ジャンル</p>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.select :genre_id, options_from_collection_for_select(@genres_name, :id, :genre_name) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <p>価格</p>
    </div>
    <div class="col-md-6">
      <div class="field">
        <%= f.number_field :price, autofocus: true, autocomplete: "price" %>円
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4">
      <%= f.submit "新規登録", class:'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/games/show.html.erb
<div class="bg-white">
  <%= flash[:notice] %>
</div>
<div class="contaier px-5 bg-white">
  <!--games#show-->
  <div class="row">
    <div class="col">
      <h2>
        <%= @game.name %>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @game.get_profile_image(200,200) %>
    </div>
    <div class="col-md-1 genre">
      <%= @game.genre.genre_name %>
    </div>
    <div class="col-md-5">
      <div><%= l @game.created_at%></div>
      <div>金額￥<%= @game.price %></div>
      <div><%= link_to "編集する", admin_edit_game_path(@game.id), :class => "btn btn-success" %></div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= @game.introduction %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h4>ユーザーのレビュー</h4>
    </div>
  </div>
  <div class="row">
    <!--game/reviews#index-->
    <div class="col review_column">
    <% @reviews.each do |review| %>
      <div class="row">
        <div class="col">
          <div class="row">
            <div class= "col">
              <%= review.user.name %>のレビュー
            </div>
          </div>
          <div class="row">
            <div class="col-md-3">
              <%= image_tag review.user.get_profile_avatar(50,50) %>
            </div>
            <div class="col-md-6">
              <%= review.review_writing %>
            </div>
            <div class="col-md-3">
              <div><%= review.comments.count %></div>
              <%= link_to "レビュー詳細へ", admin_show_review_path(review.id), :class => "btn btn-success" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>