config/routes.rb
Rails.application.routes.draw do
# ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: :all
devise_scope :user do
  get 'users/sign_up' => 'public/registrations#new', as: :new_user_registration
  post 'users/sign_up' => 'public/registrations#create', as: :create_user_registration
  get 'users/sign_in' => 'public/sessions#new', as: :new_user_session
  post 'users/sign_in' => 'public/sessions#create', as: :create_user_session
  delete 'users/sign_out' => 'public/sessions#destroy', as: :destroy_user_session
end
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: :all
devise_scope :admin do
  get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  post 'admin/sign_in' => 'admin/sessions#create', as: :create_admin_session
  delete 'admin/logout' => 'admin/sessions#destroy', as: :destroy_admin_session
end

  
  
  scope module: :public do
    root to: 'homes#top'
    delete 'bookmarks/:bookmark_id' => 'bookmarks#destroy', as: 'destroy_bookmark'
    post 'games/:game_id/bookmarks' => 'bookmarks#create', as: 'create_bookmark'
    get 'user/:id/bookmarks' => 'bookmarks#index', as: 'index_bookmark'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    post 'games/:game_id/reviews' => 'reviews#create', as: 'create_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    post 'reviews/:review_id/comments' => 'comments#create', as: 'create_comment'
    delete 'comments/:comment_id' => 'comments#destroy', as: 'destroy_comment'
    get 'games' => 'games#index'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    get 'users/mypage' => 'users#show', as: 'mypage_user'
    get 'users/edit' => 'users#edit', as: 'edit_user'
    patch 'users/update/:id' => 'users#update', as: 'update_user'#HTTPメソッドとURLが被るとルートが上から優先される(今回はupdate)ため、URLにupdateを追加して被らないようにした
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users/withdrawal'
    get '/' => 'homes#top'
    get "search" => "searches#search"
    get 'searches/index'
  end

  namespace :admin do
    get 'genres' => 'genres#index'
    post 'genres/create' => 'genres#create'
    get 'genres/:genre_id/edit' => 'genres#edit', as: 'edit_genre'
    patch 'genres/:genre_id' => 'genres#update', as: 'update_genre'
    get 'users' => 'users#index'
    get 'users/:id' => 'users#show', as: 'show_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'games' => 'games#index'
    get 'games/new' => 'games#new'
    post 'games' => 'games#create', as: 'create_game'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    delete 'games/:game_id/' => 'games#destroy', as: 'destroy_game'
    get 'games/:game_id/edit' => 'games#edit', as: 'edit_game'
    patch 'games/:game_id' => 'games#update', as: 'update_game'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    delete 'comments/:comment_id' => 'comments#destroy',as: 'destroy_comment'
    get "search" => "searches#search"
    get 'searches/index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games
  
  def self.looks(search, word)
    if search == "perfect_match"
      @genre = Genre.where("genre_name LIKE?","#{word}")
    elsif search == "forward_match"
      @genre = Genre.where("genre_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @genre = Genre.where("genre_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @genre = Genre.where("genre_name LIKE?","%#{word}%")
    else
      @genre = Genre.all
    end
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    already_genre = @genres.any?
    if already_genre
      if @genres.exists?(genre_name: @genre.genre_name)
        flash[:notice] = "すでにジャンル登録しています。"
        redirect_to admin_genres_path
      else
        @genre.save!
        flash[:notice] = "ジャンル作成に成功しました。"
        redirect_to admin_genres_path
      end
    else
      @genre.save!
      flash[:notice] = "ジャンル作成に成功しました。"
      redirect_to admin_genres_path
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:genre_id])
  end

  def update
    genre = Genre.find(params[:genre_id])
    if genre.update(genre_params)
       flash[:notice] = "ジャンルの更新に成功しました。"
       redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class ="container px-4 bg-white">
  <div class="row">
    <div class="col">
     <h3>ジャンル編集</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
    <%= form_with model: @genre, url: admin_update_genre_path do |f| %>
      <span>ジャンル名</span>
      <%= f.text_field :genre_name, autofocus: true %>
      <%= f.submit "変更を保存", class:'btn btn-success' %>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3">
      <%= link_to "ジャンル一覧へ戻る", admin_genres_path, :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="bg-white">
  <%= flash[:notice] %>
</div>
<div class ="container px-4">
  <div class="row">
    <div class="col-md-6 bg-white">
     <h3>ジャンル一覧・追加</h3>
    </div>
    <div class="col-md-6"></div>
  </div>
  <div class="row">
    <div class="col-md-6 bg-white">
    <%= form_with model: @genre, url: admin_genres_create_path do |f| %>
      <span>ジャンル名</span>
      <%= f.text_field :genre_name, autofocus: true %>
      <%= f.submit "登録", class:'btn btn-success' %>
    <% end %>
    </div>
    <div class="col-md-6"></div>
  </div>
  <div class="row">
    <div class="col-md-6 bg-white">
      <table>
        <thead>
          <tr>
            <td>ジャンル</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.genre_name %>
            </td>
            <td>
              <%= link_to admin_edit_genre_path(genre.id) do %>
                編集する
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-6"></div>
  </div>
</div>