config/routes.rb
Rails.application.routes.draw do
# ユーザー用
# URL /user/sign_in ...
devise_for :users,skip: :all
devise_scope :user do
  get 'users/sign_up' => 'public/registrations#new', as: :new_user_registration
  post 'users/sign_up' => 'public/registrations#create', as: :create_user_registration
  get 'users/sign_in' => 'public/sessions#new', as: :new_user_session
  post 'users/sign_in' => 'public/sessions#create', as: :create_user_session
  delete 'users/sign_out' => 'public/sessions#destroy', as: :destroy_user_session
end
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: :all
devise_scope :admin do
  get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
  post 'admin/sign_in' => 'admin/sessions#create', as: :create_admin_session
  delete 'admin/logout' => 'admin/sessions#destroy', as: :destroy_admin_session
end

  
  
  scope module: :public do
    root to: 'homes#top'
    delete 'bookmarks/:bookmark_id' => 'bookmarks#destroy', as: 'destroy_bookmark'
    post 'games/:game_id/bookmarks' => 'bookmarks#create', as: 'create_bookmark'
    get 'user/:id/bookmarks' => 'bookmarks#index', as: 'index_bookmark'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    post 'games/:game_id/reviews' => 'reviews#create', as: 'create_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    post 'reviews/:review_id/comments' => 'comments#create', as: 'create_comment'
    delete 'comments/:comment_id' => 'comments#destroy', as: 'destroy_comment'
    get 'games' => 'games#index'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    get 'users/mypage' => 'users#show', as: 'mypage_user'
    get 'users/edit' => 'users#edit', as: 'edit_user'
    patch 'users/update/:id' => 'users#update', as: 'update_user'#HTTPメソッドとURLが被るとルートが上から優先される(今回はupdate)ため、URLにupdateを追加して被らないようにした
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users/withdrawal'
    get '/' => 'homes#top'
    get "search" => "searches#search"
    get 'searches/index'
  end

  namespace :admin do
    get 'genres' => 'genres#index'
    post 'genres/create' => 'genres#create'
    get 'genres/:genre_id/edit' => 'genres#edit', as: 'edit_genre'
    patch 'genres/:genre_id' => 'genres#update', as: 'update_genre'
    get 'users' => 'users#index'
    get 'users/:id' => 'users#show', as: 'show_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'games' => 'games#index'
    get 'games/new' => 'games#new'
    post 'games' => 'games#create', as: 'create_game'
    get 'games/:game_id' => 'games#show', as: 'show_game'
    delete 'games/:game_id/' => 'games#destroy', as: 'destroy_game'
    get 'games/:game_id/edit' => 'games#edit', as: 'edit_game'
    patch 'games/:game_id' => 'games#update', as: 'update_game'
    get 'reviews/:review_id' => 'reviews#show', as: 'show_review'
    delete 'reviews/:review_id' => 'reviews#destroy', as: 'destroy_review'
    delete 'comments/:comment_id' => 'comments#destroy',as: 'destroy_comment'
    get "search" => "searches#search"
    get 'searches/index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameSearchSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>GameSearchSite</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if admin_signed_in? %>
            <% if request.fullpath.include? "/admin" %>
                <!--admin側のheaderを返す-->
            <li>
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/admin/logout">
                ログアウト
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/admin/users">
                会員一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/admin/games">
                ゲーム一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/admin/genres">
                ジャンル一覧
              </a>
            </li>
            <li>
              <% if admin_signed_in? %>
              <div class="search_form">
                <%= form_with url: admin_searches_index_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word %>
                    <%= f.select :range, options_for_select([['User'], ['Game']]) %>
                    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                    <%= f.submit "検索", class: "btn-sm btn-primary" %>
                  <% end %>
              </div>
              <% end %>
            </li>
            <% else %>
                <!--user側のheaderを返す-->
            <li>
              <a class="nav-link text-light" href="/users/sign_up">
                新規登録
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/games">
                ゲーム一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users/sign_in">
                ログイン
              </a>
            </li>
            <% end %>
          <% elsif user_signed_in? %>
              <!--userログイン状態の際に、表示したいheaderのメニューを記載-->
            <li>
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
                ログアウト                                    <!-- link to passの形に書き換えて解決。パスの後にclass指定することで、CSSを適応させることができる。-->
              </a>
            </li>
            <li>
              <%= link_to index_bookmark_path(current_user),class:"nav-link text-light" do %>
                ブックマーク一覧
              <% end %>
            </li>
            <li>
              <a class="nav-link text-light" href="/games">
                ゲーム一覧                                    <!-- link to passの形に書き換えて解決。パスの後にclass指定することで、CSSを適応させることができる。-->
              </a>
            </li>
            <li>
              <%= link_to mypage_user_path,class:"nav-link text-light" do %>
                マイページ
              <% end %>
            </li>
            <li>
              <% if user_signed_in? %>
              <div class="search_form">
                <%= form_with url: searches_index_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word %>
                    <%= f.select :range, options_for_select([['Game'], ['Genre']]) %>
                    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                    <%= f.submit "検索", class: "btn-sm btn-primary" %>
                  <% end %>
              </div>
              <% end %>
            </li>
          <% else %>
            <li>
              <a class="nav-link text-light" href="/users/sign_up">
                新規登録
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/games">
                ゲーム一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users/sign_in">
                ログイン
              </a>
            </li>
          <% end %>
        </div>
      </div>
     </nav>
    </header>
    <%= yield %>
    <footer>
     <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p></p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>